### ISSUE TITLE
Password has to be set two times when changing username

### ISSUE THREAD

**Issue by cjoohs** [puavo-org/puavo-web#99]
Occasionally users may want to change their username. This is possible in puavo-users and can be done by editing the existing user data. When changing the username, password has to be set again as well and it needs to be done twice. Password has to be set two times separately or one extra time when first setting is done at the same time when editing the username.

**Comment by jarmopi** [comment]
Given all the changes in the password changing system over the years, I believe this has been fixed by now. If not, open a new issue.
